### ISSUE TITLE
About how to get the previously selected knowledge

### ISSUE THREAD

**Issue by ChuanMeng** [chujiezheng/DiffKS#1]
Hey Chujie, 
There is a question about how to get the previously selected knowledge sentences.  Concretely, I'd like to know whether the previously selected knowledge sentences are directly given as the known input to the model, and instead of tracking the previously selected knowledge like [this](https://dl.acm.org/doi/pdf/10.1145/3397271.3401097).

**Comment by chujiezheng** [comment]
The previously selected knowledge sentences are NOT directly given as the input, but are tracked during the multi-turn dialog.
