### ISSUE TITLE
TypeError: Object of type 'ndarray' is not JSON serializable

### ISSUE THREAD

**Issue by wawawa1997** [chujiezheng/DiffKS#3]
Thank you for sharing. 

I encountered some problems in reproducing your code. Can you help me?

`Traceback (most recent call last):
  File "run.py", line 103, in <module>
    main(args)
  File "C:\Users\***\Desktop\DiffKS\main.py", line 31, in main
    logging.info(json.dumps(args, indent=2))
TypeError: Object of type 'ndarray' is not JSON serializable`

And I tried to modify it myself according to the error and wrote the mapping function myself.

`class MyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(MyEncoder, self).default(obj)
`
![image](https://user-images.githubusercontent.com/77926700/105633786-99e51f80-5e95-11eb-9d54-149334ca2ad2.png)

But the code conflicts with other parts of your code.

So, can you help me to slove the problem at the begining, thanks.
`Traceback (most recent call last):
  File "run.py", line 103, in <module>
    main(args)
  File "C:\Users\***\Desktop\DiffKS\main.py", line 31, in main
    logging.info(json.dumps(args, indent=2))
TypeError: Object of type 'ndarray' is not JSON serializable`

**Comment by chujiezheng** [comment]
You can print args to check which items are `np.array`, and map them into `list`.
