### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by wawawa1997** [chujiezheng/DiffKS#4]
And Can you tell me the specific version of python, CUDA, cuDNN, pytorch in your experiment in the lab? Please.

I tried the following experiment envrionment, but falled.

- Pytorch1.1
- CUDA 11.1
- Python3.7

Error
`cublas runtime error:the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu
`

**Comment by chujiezheng** [comment]
Sorry, I forgot the version. But at least I remembered that we used CUDA 10 instead of 11.
