### ISSUE TITLE
max_sent_length error

### ISSUE THREAD

**Issue by 520jefferson** [chujiezheng/DiffKS#5]
When i start the training , then i met this error as follows:
  File "run.py", line 103, in <module>
    main(args)
  File "DiffKS/main.py", line 75, in main
    model.train_process()
  File "DiffKS/seq2seq.py", line 91, in train_process
    self.train()
  File "DiffKS/seq2seq.py", line 67, in train
    self.net.forward(incoming)
  File "DiffKS/network.py", line 42, in forward
    self.genNetwork.forward(incoming)
  File "DiffKS/network.py", line 613, in forward
    if w_slice.shape[0] < self.args.max_sent_length:
  File "DiffKS/utils/storage.py", line 11, in __getattr__
    return getattr(super(Storage, self), key)
AttributeError: 'super' object has no attribute 'max_sent_length'

i wonder whether i can  set args.max_sent_length = 40 in run.py?  Is it reasonable to set the length to 40? i see the default length is 40 in the file of dataloader

**Comment by chujiezheng** [comment]
I think it is reasonable.

**Comment by 520jefferson** [comment]
I wonder if  i use the three topics (film,music, travel) data that kdconv involved (the <head entity, relation,tail entity> can be constructed into a sentense) and feed into the DiffKS, whether it will work and generate a better results than the seq2seq method ?

**Comment by chujiezheng** [comment]
I tried it last year and found DiffKS also works for KdConv. But the current input format may be greatly modified. You can just apply the idea of difference-aware knowledge selection in your own task.

**Comment by 520jefferson** [comment]
Thanks a lot , i will try step by step, firstly the retrieval with knowledge , then generate with knowledge (both triple knowledge and unstructure knowledge)，but i am a little worry the actual effect in  a real chitchat product honestly.
